### ISSUE TITLE
Move to beginning / end of file

### ISSUE THREAD

**Issue by ZwergNaseXXL** [superolmo/BigFiles#11]
Nice to have: In addition to the page forward/backward buttons and shortcuts, add move to beginning / end of file buttons and shortcuts, so users don't have to scroll through all the pages.

**Comment by superolmo** [comment]
Thanks for the idea. Yes, having the two extra shortcuts and associated buttons to go all the way up and all the way to the end makes sense.

**Comment by superolmo** [comment]
Fixed in 0.1.2.0
