### ISSUE TITLE
Perhaps BigFiles hangs N++ 7.9.0 on close?

### ISSUE THREAD

**Issue by terencemcdonnell** [superolmo/BigFiles#22]
Description of the Issue

When closing the application by clicking in the standard windows close [x] in the upper right-hand corner, application closes - but error message box pops up saying:

"Notepad++ : a free (GNU) source code editor has stopped working
A problem caused the program to stop working correctly. Please close the program.

[Close the program] [Debug the program]"

Steps to Reproduce the Issue

Open the application
Close the application
Expected Behavior

Expected to close silently

Actual Behavior

Debug Information

Notepad++ v7.9 (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Users\E022019\Documents\Apps\NPP\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 1809
OS Build : 17763.1457
Current ANSI codepage : 1252
Plugins : BigFiles.dll CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFavorites.dll NPPJSONViewer.dll NppTextFX.dll NppXmlTreeviewPlugin.dll PoorMansTSqlFormatterNppPlugin.dll _CustomizeToolbar.dll

FYI - issue resolved - information for anyone that googled into this thread looking for info - by a process of elimination (disabling and enabling plugins), I determined that the culprit was the "BigFiles" plugin - doesn't seem to want to play nice with latest version (I just upgraded to 7.9.0).

Disabled that plugin (renamed BigFIle directory in Plugins directory to xBigFile) and issue was resolved.

Thanks
 @ArkadiuszMichalski
  
Contributor
ArkadiuszMichalski commented 2 hours ago
@terencemcdonnell You can report this in https://github.com/superolmo/BigFiles/issues.

**Comment by superolmo** [comment]
Thank you for opening an issue. I have not updated to 7.9 yet but I will soon.

**Comment by superolmo** [comment]
Steps:
- Download and extract the portable version of the Notepad++ v7.9.0
- Open Notepad++ and Install the BigFiles plugin
- Close Notepad++
- Open Notepad++
- Close Notepad++, **no errors**.
I will test with the installed version of the program.

**Comment by ArkadiuszMichalski** [comment]
Problem also may occure because a lot of plugins used by OP. @terencemcdonnell can you dissable all plugins and test only with BigFiles?

**Comment by YouriAndropov** [comment]
I have the same issue. It works well on my own computer, but on any windows virtual machine I try, I have this crash at shutdown.
Even if BigFiles is the only plugin installed.

Windows events report:
Faulting application name : notepad++.exe, version 7.9.1.0, time stamp: 0x5f9f4e46
Faulting module name : ntdll.dll, version 10.0.14393.3630, time stamp: 0x5e8d4386
Exception code: 0xc0000374 --> **STATUS_HEAP_CORRUPTION**
Fault offset: 0x0000000000f7a13

**Comment by superolmo** [comment]
> I have the same issue. It works well on my own computer, but on any windows virtual machine I try, I have this crash at shutdown.
> Even if BigFiles is the only plugin installed.
> 
> Windows events report:
> Faulting application name : notepad++.exe, version 7.9.1.0, time stamp: 0x5f9f4e46
> Faulting module name : ntdll.dll, version 10.0.14393.3630, time stamp: 0x5e8d4386
> Exception code: 0xc0000374 --> **STATUS_HEAP_CORRUPTION**
> Fault offset: 0x0000000000f7a13

Thank you for reporting this. I will build a Windows virtual machine and try to reproduce the heap corruption issue. Sounds like a bad file pointer.

**Comment by Darthagnon** [comment]
I was having the same problem (Npp v7.8.9 x86/32bit and upwards, I believe); was driving me crazy.

Every time I closed Npp, it would crash and popup with a message. I narrowed it down to BigFiles causing the crash. I do use a ton of other plugins, too.

My system:
Npp v7.8.9 up to latest 7.9.1 x86 32bit
Win10 v1709

**Comment by superolmo** [comment]
I set up a Windows 10 Pro 20H2 virtual machine using Virtual Box. Installed Notepad++ upstream version 7.9.1. 64bit and the BigFiles plugin v0.1.2. So far I have not encountered any issue. I have opened both files on the Guest and Host systems.

Please add to this thread your configuration to reproduce the issue.

**Comment by superolmo** [comment]
> I have the same issue. It works well on my own computer, but on any windows virtual machine I try, I have this crash at shutdown.
> Even if BigFiles is the only plugin installed.
> 
> Windows events report:
> Faulting application name : notepad++.exe, version 7.9.1.0, time stamp: 0x5f9f4e46
> Faulting module name : ntdll.dll, version 10.0.14393.3630, time stamp: 0x5e8d4386
> Exception code: 0xc0000374 --> **STATUS_HEAP_CORRUPTION**
> Fault offset: 0x0000000000f7a13

@YouriAndropov Could you give me some information on how to reproduce the issue. I tried with Virtual Box and it did not seem to have any issue.

**Comment by superolmo** [comment]
I think I found the error. It is in the cleanup function that runs on shutdown. I will post an updated version soon with few enhancements for both x86 and x64.

**Comment by superolmo** [comment]
I have added an intermediate release in the Dev branch. This should fix the error. Could you please test it?
Right click below link and replace the older BigFiles.dll under Notepad++ pluging folder:
[x64 Download](https://github.com/superolmo/BigFiles/raw/dev/x64/Release/BigFiles.dll) 
[x86 Download](https://github.com/superolmo/BigFiles/raw/dev/x86/Release/BigFiles.dll)

**Comment by YouriAndropov** [comment]
Hello, I did a test, and it worked fine, no more crashes on exit.

Congrats !
